Revert "metricbeat/ci: update metricbeat version"
This reverts commit ece1ea89c0be51e398ce991e348f01707ce077fa.

This change is producing an error in the CI
Exception: Key 'beat.stats.info.version' found in event is not documented!

Reverting to get to a stable build.