Fix cisco.ios pipeline bug for syslog input
This fixes a problem with the pipeline when being used with the syslog input (rather than the files that we test with). The dissect processor tries to set a field that is already added by the syslog input.

    GoError: cannot override existing key with `event.severity`