test: replace go-test/deep with google/go-cmp (#39902)
go-test/deep is only used once and can be safely replaced with
google/go-cmp which is already used for other tests.
The error message changes a bit.

Before:
--- FAIL: TestJsonToSynthEvent (0.00s)
    --- FAIL: TestJsonToSynthEvent/a_valid_line (0.00s)
        synthexec_test.go:94: [TimestampEpochMicros: 7.165676811882693e+18 != 1.7165676811882693e+19]
FAIL
FAIL    github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser/synthexec 0.180s
FAIL

After:
--- FAIL: TestJsonToSynthEvent (0.00s)
    --- FAIL: TestJsonToSynthEvent/a_valid_line (0.00s)
        synthexec_test.go:95:   &synthexec.SynthEvent{
                ... // 3 identical fields
                Step:                 &{Name: "Go to home page", Status: "succeeded"},
                Journey:              &{Name: "inline", ID: "inline"},
            -   TimestampEpochMicros: 7.165676811882693e+18,
            +   TimestampEpochMicros: 1.7165676811882693e+19,
                Payload:              {"duration_ms": float64(3472), "source": string("async ({page, params}) => {await page.goto('http:
                Blob:                 "",
                ... // 1 ignored and 5 identical fields
              }

FAIL
FAIL    github.com/elastic/beats/v7/x-pack/heartbeat/monitors/browser/synthexec 0.197s
FAIL