Update the golangci-lint to 2.12.2 to support Go 1.26 (#50918) (#50921)
After updating Go to version 1.26 the linter stopped working with the
error:

```
Error: can't load config: the Go language version (go1.25) used to
build golangci-lint is lower than the targeted Go version (1.26.3)
```

(cherry picked from commit d761c170359db8d23d61c22e9161202d744f2cbc)

Co-authored-by: Denis <denis.rechkunov@elastic.co>