python requirements: bump protobuf version to match 7494535
The change in 7494535 did not update these requirements, resulting in
inconsistent requirements and doc check failure:

ERROR: Cannot install protobuf==3.19.4 and protobuf==3.19.5 because these package versions have conflicting dependencies.