Cherry-pick #7718 to 6.x: Fetch github.com/docker/libcompose for libbeat go tests (#8288)
* Fetch github.com/docker/libcompose for libbeat go tests

(cherry picked from commit df3f0eaeb3abcc54125f343b8a986218ba0589f4)

* Fetch github.com/docker/libcompose before testing libbeat

The libbeat tests were failing to compile and the error was uncaught. The cause was that github.com/docker/libcompose was not installed prior to running `go test` (relates to elastic/beats#5050). This moves `go get github.com/docker/libcompose` earlier in the script.

A separate change will be made in another commit to always report the `go test` exit code rather than the one from `go-junit-report`.

(cherry picked from commit c8008ff357440266c1c7c3d2b811250fa1fbdb75)

* Fix arg type used in fmt.Errorf

    PS C:\Gopath\src\github.com\elastic\beats\libbeat\common\file> go test -json -v .
    # github.com/elastic/beats/libbeat/common/file
    .\file_windows.go:105: Errorf format %s has arg pathp of wrong type *uint16
    FAIL    github.com/elastic/beats/libbeat/common/file [build failed]

(cherry picked from commit 4ed9318825a05b57bf732325cfd09a87735655f8)