Update docs.asciidoc
Updated the description to include a note on the first setup required permissions. When testing this with a customer, the first setup thrown the following error:

```
2025-02-03T19:54:05.876Z ERROR [input.httpjson-cursor] v2/input.go:115 Error while processing http request: failed to execute http client.Do: server responded with status code 403: {"error":{"code":"Forbidden","message":"Missing application roles. API required roles: Incident.Read.All,Incident.ReadWrite.All, application roles:
```
So I added a note to make it clear that the first setup needs some permissions to access the file system.