Fix TestTimeString
The sub-tests are not independent because SetTimestampPrecision
modifies a global. So this modifies SetTimestampPrecision to provide
a way to reset the global value to its default. Now each test
sets the global before executing.

There error was:

 === RUN   TestTimeString/empty_config
    datetime_test.go:158:
        	Error Trace:	datetime_test.go:158
        	Error:      	Not equal:
        	            	expected: "2015-03-01T11:19:05.000Z"
        	            	actual  : "2015-03-01T11:19:05.000001Z"