fix packetbeat devices command (#6307)
The -devices flag is not valid, it yields:

/usr/share/packetbeat/bin/packetbeat -devices
Error: unknown flag: --devices

The command is "packetbeat devices"

(cherry picked from commit b8ded9b4af917d8f5946031a39852b263306bc2c)