Fix arg type used in fmt.Errorf
    PS C:\Gopath\src\github.com\elastic\beats\libbeat\common\file> go test -json -v .
    # github.com/elastic/beats/libbeat/common/file
    .\file_windows.go:105: Errorf format %s has arg pathp of wrong type *uint16
    FAIL    github.com/elastic/beats/libbeat/common/file [build failed]

(cherry picked from commit 4ed9318825a05b57bf732325cfd09a87735655f8)