Downgrade PyYaml to 5.3.1
Upgrading to 6.0.1 did not work because there is a dependency conflict with docker-compose.

When using the version 5.4.1 the following error message appears when trying to run `pip install -r requirements.txt`

```
AttributeError: cython_source
```

Related issue: https://github.com/yaml/pyyaml/issues/601