Libbeat test fixes
This has a few fixes to python system tests under libbeat/tests/system.

assert_docs_written_to_alias had an invalid assertion ever since Elasticsearch
changed the format of the hits count to allow for track_total_hits false. Many
tests were using this assertion even when not indexing any events so the hit
count would always be zero so I removed the assertion from those tests.

In other tests I was getting spurious failures because _search was being called
before the index was refreshed to allow the documents to be search able. So I
added an explicit /_refresh to fix the issue.

I changed create_kibana_space to allow a 409 response code so you can run the
tests more than once against a Kibana instance.

I fixed an assertion on the mode bits of a file since the format of octal numbers is
always prefixed with '0o' now.

And I fixed the libbeat keystore tests by encoding the secret string to binary
before calling os.write. This fixed this error:

```
======================================================================
ERROR: Add a secret to the store using stdin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/akroh/go/src/github.com/elastic/beats/libbeat/tests/system/test_cmd_keystore.py", line 130, in test_keystore_add_secret_from_stdin
    exit_code = self.add_secret("willnotdelete")
  File "/Users/akroh/go/src/github.com/elastic/beats/libbeat/tests/system/keystore.py", line 29, in add_secret
    os.write(proc.stdin_write, value)
TypeError: a bytes-like object is required, not 'str'
```